Script started on 2015年03月10日 (週二) 17時28分42秒
]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ h3403039[C[1P3403039H3403039[C[C[C[C[C1039[C[C[C; pwd[K[K[Kbenjamin850422
H34031039: command not found
benjamin850422: command not found
]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ whoami; pwd
H34031039
/home/H34031039
]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ git cin[K[Konfig -1
error: unknown switch `1'
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 adds a new variable: name value
    --unset               removes a variable: name [value-regex]
    --unset-all           removes all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            opens an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte

]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ git config -1[Kl
]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ git clone https://github.com/BenjaminChenTW/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ git clone https://github.com/BenjaminChenTW/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ ld[Ks
[0m[01;34mlab1[0m  lab1.script
]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ exit

Script done on 2015年03月10日 (週二) 17時39分23秒
