Script started on 2015年03月12日 (週四) 18時07分30秒
]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ git clone https://github.com/BenjaminChenTW/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K[2Pwhoami; pwd[5Plogoutbenjamin850422[8Plogoutbenjamin850422[8Plogoutwhoami; pwd
H34031039
/home/H34031039
]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ whoami; pwdgit clone https://github.com/BenjaminChenTW/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K[2Pwhoami; pwdgit config -l
user.name=BenjamnChenTW
user.email=s910190benjamin@gmail.com
]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ git config -l[2Pwhoami; pwdgit config -l[Kgit config -l[2Pwhoami; pwdgit clone https://github.com/BenjaminChenTW/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[Klone https://github.com/BenjaminChenTW/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 16, done.[K
remote: Compressing objects:   7% (1/14)   [Kremote: Compressing objects:  14% (2/14)   [Kremote: Compressing objects:  21% (3/14)   [Kremote: Compressing objects:  28% (4/14)   [Kremote: Compressing objects:  35% (5/14)   [Kremote: Compressing objects:  42% (6/14)   [Kremote: Compressing objects:  50% (7/14)   [Kremote: Compressing objects:  57% (8/14)   [Kremote: Compressing objects:  64% (9/14)   [Kremote: Compressing objects:  71% (10/14)   [Kremote: Compressing objects:  78% (11/14)   [Kremote: Compressing objects:  85% (12/14)   [Kremote: Compressing objects:  92% (13/14)   [Kremote: Compressing objects: 100% (14/14)   [Kremote: Compressing objects: 100% (14/14), done.[K
remote: Total 16 (delta 1), reused 16 (delta 1), pack-reused 0[K
Unpacking objects:   6% (1/16)   Unpacking objects:  12% (2/16)   Unpacking objects:  18% (3/16)   Unpacking objects:  25% (4/16)   Unpacking objects:  31% (5/16)   Unpacking objects:  37% (6/16)   Unpacking objects:  43% (7/16)   Unpacking objects:  50% (8/16)   Unpacking objects:  56% (9/16)   Unpacking objects:  62% (10/16)   Unpacking objects:  68% (11/16)   Unpacking objects:  75% (12/16)   Unpacking objects:  81% (13/16)   Unpacking objects:  87% (14/16)   Unpacking objects:  93% (15/16)   Unpacking objects: 100% (16/16)   Unpacking objects: 100% (16/16), done.
]0;H34031039@2015cpp: ~H34031039@2015cpp:~$ exit

Script done on 2015年03月12日 (週四) 18時08分04秒
